import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './AuthContext';
import Navbar from '@/components/navbar';
import { getCart } from '@/lib/actions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cart: any[] = await getCart();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar cart={cart} />
          <main className="mt-20 mx-auto max-w-6xl">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
