import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './AuthContext';
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Retro Store App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-black dark:text-white dark:bg-neutral-900`}
      >
        <AuthProvider>
          <Navbar />
          <main className="mt-20 mx-auto max-w-6xl">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
